imports:
  - php

build:
  environment:
    php: "8.1"
  tests:
    override:
      - command: "vendor/bin/phpunit --coverage-clover=clover.xml --exclude-group flaky"
        coverage:
          file: "build/logs/clover.xml"
          format: "clover"
      - php-scrutinizer-run
