name: ci

on: [push, pull_request]

jobs:

  tests:
    name: ${{ matrix.operating-system }} with PHP ${{ matrix.php-version }}
    
    strategy:
      matrix:
        operating-system:
          - 'ubuntu-latest'
        php-version: 
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: |
          composer update --no-interaction --no-progress --optimize-autoloader

      - name: Run tests with PHPUnit
        run: |
          vendor/bin/phpunit
